# Generated by Django 5.2.8 on 2025-11-08 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='new_user_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_firstname', models.CharField(max_length=50)),
                ('for_lastname', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=20)),
                ('office', models.CharField(max_length=10)),
                ('network_access', models.TextField()),
                ('email_groups', models.TextField()),
                ('addtional_email', models.TextField()),
                ('supervisor', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
