# Generated by Django 5.2.8 on 2025-11-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_user_request',
            name='campus',
        ),
        migrations.AddField(
            model_name='new_user_request',
            name='ac5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='new_user_request',
            name='moodle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='new_user_request',
            name='mystudies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='new_user_request',
            name='otrs',
            field=models.BooleanField(default=False),
        ),
    ]
