# Generated by Django 5.2.8 on 2025-11-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0002_remove_new_user_request_campus_new_user_request_ac5_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_user_request',
            name='department',
        ),
        migrations.AlterField(
            model_name='new_user_request',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
