# Generated by Django 5.2.8 on 2025-11-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0003_remove_new_user_request_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_user_request',
            name='campus',
            field=models.CharField(choices=[('VAL', 'Valendar'), ('DUS', 'Düsseldorf')], default='VAL', max_length=3),
        ),
    ]
