# Generated by Django 5.2.8 on 2025-11-08 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0004_new_user_request_campus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new_user_request',
            old_name='email_groups',
            new_name='mail_distribution_lists',
        ),
    ]
