# Generated by Django 5.2.8 on 2025-11-08 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0005_rename_email_groups_new_user_request_mail_distribution_lists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUserRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('for_firstname', models.CharField(max_length=50)),
                ('for_lastname', models.CharField(max_length=50)),
                ('campus', models.CharField(choices=[('VAL', 'Valendar'), ('DUS', 'Düsseldorf')], default='VAL', max_length=3)),
                ('job_title', models.CharField(max_length=20)),
                ('office', models.CharField(max_length=10)),
                ('supervisor', models.CharField(max_length=20)),
                ('network_access', models.TextField(default='not needed')),
                ('mail_distribution_lists', models.TextField(default='not needed')),
                ('addtional_email', models.TextField(default='not needed')),
                ('mystudies', models.BooleanField(default=False)),
                ('ac5', models.BooleanField(default=False)),
                ('moodle', models.BooleanField(default=False)),
                ('otrs', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='new_user_request',
        ),
    ]
