# Generated by Django 5.2.8 on 2025-11-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0006_newuserrequest_delete_new_user_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuserrequest',
            name='department',
            field=models.CharField(default='', max_length=10),
        ),
    ]
