# Generated by Django 5.2.8 on 2025-11-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0007_newuserrequest_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuserrequest',
            name='start_date',
            field=models.DateField(auto_now=True),
        ),
    ]
