# Generated by Django 5.2.8 on 2025-11-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0008_newuserrequest_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuserrequest',
            old_name='addtional_email',
            new_name='additional_email',
        ),
    ]
