# Generated by Django 5.2.8 on 2025-11-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0009_rename_addtional_email_newuserrequest_additional_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuserrequest',
            name='start_date',
            field=models.DateField(),
        ),
    ]
