# Generated by Django 5.2.8 on 2025-11-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0010_alter_newuserrequest_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuserrequest',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='newuserrequest',
            name='department',
            field=models.CharField(default='', max_length=20),
        ),
    ]
