# Generated by Django 5.2.8 on 2025-11-09 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_management', '0011_remove_newuserrequest_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuserrequest',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
